# Bindu_Gadagottu_ML

# DEVINCEPT

## Machine_Learning_concepts

## Linear Regression


###  1. Import packages and classes

In [5]:
import numpy as np
from sklearn.linear_model import LinearRegression

### 2. Provide data

In [6]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [7]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [8]:
print(y)

[ 5 20 14 32 22 38]


In [10]:
x.shape

(6, 1)

In [11]:
y.shape

(6,)

###  3. Create a model and fit it

In [12]:
model = LinearRegression()

In [13]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
model = LinearRegression().fit(x, y)

###  4. Get results

In [15]:
r_sq = model.score(x, y)

In [16]:
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756137479542


In [17]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [18]:
print('slope:', model.coef_)

slope: [0.54]


In [19]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))

In [20]:
print('intercept:', new_model.intercept_)

intercept: [5.63333333]


###  5. Predict response

In [21]:
y_pred = model.predict(x)

In [22]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [23]:
y_pred = model.intercept_ + model.coef_ * x

In [24]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [25]:
x_new = np.arange(5).reshape((-1, 1))

In [26]:
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [27]:
y_new = model.predict(x_new)

In [28]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
